Production ready, canonical code
singpass/myinfo-connector-dotnet pull request #1
Opened 2022-01-11 11:04 UTC by brent-ir

2022-01-13 08:04 UTC, 177alcol177 requested changes
Noticed that interpolated string is used in most cases thus proposed to change a few more for consistency and readability.

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +| Purpose | The text passed to the OAuth to inform the user what
```suggestion
| Purpose | The text passed to the OAuth service to inform the user about the purpose to get his/her data. This will be shown to the user when requesting for his/her consent.
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +| PrivateCertificateFilename | Path of the .p12 file that holds the private key. Absolute or relative path to assembly |
If we are going to rename this then `PrivateKeyFilename` may be more appropriate as private certificate can also mean SSL certificate issued by private CA.
```suggestion
| PrivateKeyFilename | Path of the .p12 file that holds the private key. Absolute or relative path to assembly |
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +| PrivateCertificatePassword | Password of your private key p12 file. |
Related to above.
```suggestion
| PrivateKeyPassword | Password of your private key p12 file. |
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +| ClientAppId | Unique ID provided upon approval of your application to use MyInfo. For our sample application, it is **STG2-MYINFO-SELF-TEST** |
Referencing OAuth, will prefer to stick to `ClientId`.
```suggestion
| ClientId | Unique ID provided upon approval of your application to use MyInfo. For our sample application, it is **STG2-MYINFO-SELF-TEST** |
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +| ClientAppPassword | Secret key provided upon approval of your application to use MyInfo. For our sample application, it is **44d953c796cccebcec9bdc826852857ab412fbe2** |
Referencing OAuth, will prefer to stick to `ClientSecret`.
```suggestion
| ClientSecret | Secret key provided upon approval of your application to use MyInfo. For our sample application, it is **44d953c796cccebcec9bdc826852857ab412fbe2** |
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +### 2. Construct the URL that the user should be redirected to
```suggestion
### 2. Construct the authorise URL 
The authorise URL includes the redirect URL so that the service can redirect the user to it after granting consent.
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +// Receive the callback and get the `authcode`
```suggestion
var authoriseUrl = connector.GetAuthoriseUrl(redirectUrl);
// Invoke the authorise endpoint with authoriseUrl. Receive the callback and get the `authcode`
```

2022-01-13 08:04 UTC, 177alcol177 commented on README.md
> +### 3. Retrieve the persons data
```suggestion
### 3. Retrieve the person's data
```

2022-01-13 08:04 UTC, 177alcol177 commented on build/GlobalAssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © 2021")]
```suggestion
[assembly: AssemblyCompany("Government of Singapore")]
[assembly: AssemblyCopyright("Copyright © 2022")]
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnectorConfig.cs
> +            if (string.IsNullOrEmpty(PersonUrl)) messages.Add($"PersonUrl missing or empty");
Since these are static string without variables, `$` seems redundant.
```suggestion
            if (string.IsNullOrEmpty(PrivateCertificateFilename)) messages.Add("PrivateCertificateFilename missing or empty");
            if (string.IsNullOrEmpty(PrivateCertificatePassword)) messages.Add("PrivateCertificatePassword missing or empty");
            if (string.IsNullOrEmpty(PublicCertificateFilename)) messages.Add("PublicCertificateFilename missing or empty");
            if (string.IsNullOrEmpty(ClientAppId)) messages.Add("ClientAppId missing or empty");
            if (string.IsNullOrEmpty(ClientAppPassword)) messages.Add("ClientAppPassword missing or empty");
            if (string.IsNullOrEmpty(AttributeCsv)) messages.Add("AttributeCsv missing or empty");
            if (string.IsNullOrEmpty(Environment)) messages.Add("Environment missing or empty");
            if (string.IsNullOrEmpty(TokenUrl)) messages.Add("TokenUrl missing or empty");
            if (string.IsNullOrEmpty(PersonUrl)) messages.Add("PersonUrl missing or empty");
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/Properties/AssemblyInfo.cs
> +[assembly: AssemblyDescription("SingPass integration library")]
```suggestion
[assembly: AssemblyTitle("MyInfoConnector")]
[assembly: AssemblyDescription(".Net Connector for MyInfo")]
```

2022-01-13 08:04 UTC, 177alcol177 commented on tst/MyInfoConnector.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyDescription("SingPass integration library")]
```suggestion
[assembly: AssemblyTitle("MyInfoConnector")]
[assembly: AssemblyDescription(".Net Connector for MyInfo")]
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/packages.config
> +  <package id="Newtonsoft.Json" version="12.0.1" targetFramework="net48" />
Can we use the latest `13.0.1` which is used in your test or is there a reason to stick to `12.0.1`?

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.csproj
> +      <HintPath>..\..\packages\Newtonsoft.Json.12.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
Can we use the latest `13.0.1` which is used in your test or is there a reason to stick to `12.0.1`?

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.cs
> +                baseParams = $"{ApplicationConstant.APP_ID}={_config.ClientAppId}&{ApplicationConstant.CLIENT_ID}={_config.ClientAppId}&{ApplicationConstant.CLIENT_SECRET}={_config.ClientAppPassword}
Extra `;` at the end.
```suggestion
                baseParams = $"{ApplicationConstant.APP_ID}={_config.ClientAppId}&{ApplicationConstant.CLIENT_ID}={_config.ClientAppId}&{ApplicationConstant.CLIENT_SECRET}={_config.ClientAppPassword}&{ApplicationConstant.CODE}={authCode}&{ApplicationConstant.GRANT_TYPE}={ApplicationConstant.AUTHORIZATION_CODE}&{ApplicationConstant.NONCE}={nonce}&{ApplicationConstant.REDIRECT_URI}={redirectUri}&{ApplicationConstant.SIGNATURE_METHOD}={ApplicationConstant.RS256}&{ApplicationConstant.STATE}={state}&{ApplicationConstant.TIMESTAMP}={timestamp}";
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.cs
> +                specificPersonUrl = specificPersonUrl + "?" + ApplicationConstant.CLIENT_ID + "=" + _config.ClientAppId + "&" + ApplicationConstant.ATTRIBUTE + "=" + _config.AttributeCsv;
```suggestion
                specificPersonUrl = $"{specificPersonUrl}?{ApplicationConstant.CLIENT_ID}={_config.ClientAppId}&{ApplicationConstant.ATTRIBUTE}={_config.AttributeCsv}";
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.cs
> +                var specificPersonUrl = _config.PersonUrl + "/" + uinFin + "/";
```suggestion
                var specificPersonUrl = $"{_config.PersonUrl}/{uinFin}/";
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.cs
> +                        string headers = ApplicationConstant.APP_ID + "=\"" + _config.ClientAppId + "\"," + ApplicationConstant.NONCE + "=\"" + nonce + "\"," + ApplicationConstant.SIGNATURE_METHOD +
```suggestion
                        string headers = $"{ApplicationConstant.APP_ID}=\"{_config.ClientAppId}\",{ApplicationConstant.NONCE}=\"{nonce}\",{ApplicationConstant.SIGNATURE_METHOD}=\"{ApplicationConstant.RS256}\",{ApplicationConstant.SIGNATURE}=\"{signature}\",{ApplicationConstant.TIMESTAMP}=\"{timestamp}\"";
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnector.cs
> +                     "&redirect_uri=" + Uri.EscapeDataString(redirectUri);
```suggestion
            var args = $"?client_id={_config.ClientAppId}&attributes={_config.AttributeCsv}&purpose={Uri.EscapeDataString(purpose)}&redirect_uri={Uri.EscapeDataString(redirectUri)}";
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnectorConfig.cs
> +                    messages.Add("PrivateCertificateFilename failed to load - " + e.Message);
```suggestion
                    messages.Add($"PrivateCertificateFilename failed to load - {e.Message}");
```

2022-01-13 08:04 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnectorConfig.cs
> +                    messages.Add("PublicCertificateFilename failed to load - " + e.Message);
```suggestion
                    messages.Add($"PublicCertificateFilename failed to load - {e.Message}");
```

2022-01-13 11:20 UTC, brent-ir commented on src/MyInfoConnector/MyInfoConnectorConfig.cs
> +                    messages.Add("PublicCertificateFilename failed to load - " + e.Message);
thanks @177alcol177 - addressed all issues. Either committed in PR or noted with a 👍 (don't like resolving other peoples conversations.

As a bonus I added a console app to help do integration tests

https://user-images.githubusercontent.com/37363601/149321006-6d91f043-85d8-45aa-9576-6ba546e89095.mp4

2022-01-14 03:49 UTC, 177alcol177 commented on tst/MyInfoConnector.Console/Properties/AssemblyInfo.cs
> +[assembly: AssemblyDescription("SingPass integration library")]
Naming here still follows the previous one.
```suggestion
[assembly: AssemblyTitle("MyInfoConnector")]
[assembly: AssemblyDescription(".Net Connector for MyInfo")]
```

2022-01-14 03:52 UTC, 177alcol177 commented on src/MyInfoConnector/MyInfoConnectorConfig.cs
> +                    messages.Add("PublicCertificateFilename failed to load - " + e.Message);
Thanks for following up on the PR comments and for the console app for integration test. Only a few small changes left. Or is it ok for me to commit them if you don't mind.

2022-01-14 06:01 UTC, merged